<a href="https://colab.research.google.com/github/Reshma620/Ultimate-Data-Science-Toolkit---From-Python-Basics-to-GenerativeAI/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#list vs numpy array
nums_list=list(range(100000))

for idx in range (len(nums_list)):
  nums_list[idx]=nums_list[idx]**2
#print(nums_list)


CREATING NUMPY ARRAYS


In [ ]:
import numpy as np

In [ ]:
#np.array([values])
arr=np.array([1,2,3,4,5]) #1D-array vector
arr

array([1, 2, 3, 4, 5])

In [ ]:
# 2D Array (matrix)
mat=np.array([
    [1,2,3],
    [4,5,6]
])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(arr.nbytes) # nbytes:tells you how much memory (in bytes) is used by an array or object
print(mat.dtype)  # dtype: tells the data type

print(type(arr))

40
int64
<class 'numpy.ndarray'>


In [ ]:
# np.zeroes
zeroes= np.zeros(15)  # it will create an 1D array of 25 elemnts that are zeroes.
zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# np.zeros((row, coloumn))
zeros=np.zeros((4,6))
zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
zeros=np.zeros(6, dtype=np.int32)
zeros

array([0, 0, 0, 0, 0, 0], dtype=int32)

In [ ]:
# np.ones
ones=np.ones(8)
ones

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# np.ones((rows,col))
ones=np.ones((3,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
ones=np.ones(5, dtype=np.int16)# int16 means it contain 2 bytes
print(ones)
ones=ones.nbytes
ones


[1 1 1 1 1]


10

In [ ]:
#np.arange():It is used to create an array with a sequence of numbers.

#slicing: [start:stop:step]
#starts from 0 till -1, by step

# 1D array can be created using only arange()
array=np.arange(11) # start
print(array)

nums=np.arange(6,12) # start and stop
print(nums)

x=np.arange(3,16,2) # start, stop and step
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11]
[ 3  5  7  9 11 13 15]


In [ ]:
# np.linspace():It is used to generate evenly spaced numbers between two values.

linear_arr=np.linspace(4,12,num=6)
linear_arr

array([ 4. ,  5.6,  7.2,  8.8, 10.4, 12. ])

BASIC ATTRIBUTES


In [ ]:
# Shape    : (2, 3)
# Datatype (dtype) : int64
# Dimensions (ndim) : 2
# Number of elements (size) : 6
# Total memory (nbytes)  : 48
# Bytes per element (itemsize): 8

arr=np.array([1,2,3,4,5])

mat_a=np.array([
    [1,2,3],
     [5,6,7]])

In [ ]:
#shape
import numpy as np
arr=np.array([1,2,3,4,5])
print("shape:",arr.shape)

mat_a=np.array([
    [1,2,3],
     [5,6,7]])
print("shape of matrix:",mat_a.shape)


shape: (5,)
shape of matrix: (2, 3)


In [ ]:
#datatypes
print(arr.dtype)
print(mat_a.dtype)

int64
int64


In [ ]:
#number of dimensions
print(arr.ndim)
print(mat_a.ndim)

1
2


In [ ]:
#number of elements
print('*'*5,"size",'*'*5)
print(arr.size)
print(mat_a.size)

***** size *****
5
6


In [ ]:
#total memory (bytes) :48
print("*"*5,"Total bytes","*"*5)
print(arr.nbytes)
print(mat_a.nbytes)


***** Total bytes *****
40
48


In [ ]:
# Bytes per element
print("*"*5,"Bytes per element","*"*5)
print(arr.itemsize)
print(mat_a.itemsize)


***** Bytes per element *****
8
8


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
print (a)

[1 2 3 4 5]


In [ ]:
import numpy as np
test=np.array([1,2,3,4,'A'])
test

array(['1', '2', '3', '4', 'A'], dtype='<U21')

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr.dtype)
arr=np.array([1.0,4,4.6])
arr.dtype


int64


dtype('float64')

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr

# 2*3
# 3*2
# 6*1

array([1, 2, 3, 4, 5, 6])

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr.reshape((2,3)))
print("*"*10)
print(arr.reshape((3,2)))
print("*"*10)
print(arr.reshape((6,1)))




[[1 2 3]
 [4 5 6]]
**********
[[1 2]
 [3 4]
 [5 6]]
**********
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
import numpy as np
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
np.transpose(arr)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
# row major matrix
# column major matrix

Vectorized operations


In [ ]:
# add 2 to each elment of a.
import numpy as np
a=np.array([
    [1,2,3],
    [4,5,6],
     [7,8,9]
    ])
b=np.array([
    [9,8,6],
    [7,5,4],
    [3,2,1]
    ])
print(a+2)
print(b+2)


[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[11 10  8]
 [ 9  7  6]
 [ 5  4  3]]


In [ ]:
import numpy as np
nums=[1,2,3,4]
x=2
#nums=nums+2
for idx in range(len(nums)):
  nums[idx]=nums[idx]+x
nums

[3, 4, 5, 6]

In [ ]:
import numpy as np
a*3

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [ ]:
#elemnt wise edition a and b
import numpy as np
res=a+b
res

array([[10, 10,  9],
       [11, 10, 10],
       [10, 10, 10]])

In [ ]:
# elemnt wise multiplication
import numpy as np
res=a*b
res

array([[ 9, 16, 18],
       [28, 25, 24],
       [21, 16,  9]])

In [ ]:
# element wise subtraction
import numpy as np
res=a-b
res

array([[-8, -6, -3],
       [-3,  0,  2],
       [ 4,  6,  8]])

In [ ]:
# square each elemnt
import numpy as np
a**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
 # divide b by a
import numpy as np
b/a

array([[9.        , 4.        , 2.        ],
       [1.75      , 1.        , 0.66666667],
       [0.42857143, 0.25      , 0.11111111]])

In [ ]:
# Modulus operation
import numpy as np
a%b

array([[1, 2, 3],
       [4, 0, 2],
       [1, 0, 0]])

In [ ]:
# Add scalar
import numpy as np
a+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
# compare a>2
# insexing-> boolean->filters
import numpy as np
a>2

array([[False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

INDEXING AND SLICING


In [ ]:
import numpy as np
name= 'Reshma kumari'
print(name[0:len(name)+1:3])

Rh mi


In [ ]:
import numpy as np
arr=np.array([12,13,14,16])
print(arr)
print(arr[2])
print(arr[0:4:2])
print(arr[::-1])

[12 13 14 16]
14
[12 14]
[16 14 13 12]


In [ ]:
import numpy as np
mat=np.array([
    [1,2,3],  #row 0, col- 0,1,2
    [4,5,6],  #row 1, col- 0,1,2
    [7,8,9]   #row 2, col- 0,1,2
   ])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
import numpy as np
mat[2,1]
mat[0:2,1]
mat[0:2,::-1]

array([[3, 2, 1],
       [6, 5, 4]])

In [ ]:
# Aggregate funcion:
#stats:
#Box plot: outliner detection (Anomly/error),  : box plot is a graphical representation of data that shows:
#minimum :
#first quartile (Q1)
#median (Q2)
#third quartile (Q3)
#maximum
#outliers

#Skewness from Box Plot
#Median near center → symmetric
#Median closer to Q1 → right-skewed
#Median closer to Q3 → left-skewed

# 1 2 3 4 5 100-> mean()=19.167, median()= 3.5,
# 1,2,3,4,5---------19.167--------100

#np.sum()
#np.mean()
#np.median()
#np.min()
#np.max()
#np.std()
#np.var()
#np.quantile()
#np.percentile()

In [ ]:
import numpy as np
nums=np.array([100,345,123,545,789])
nums

array([100, 345, 123, 545, 789])

In [ ]:
# box plot-> min, max, mean/median
import numpy as np
print(nums.min())
print(nums.max())
print(nums.mean())
print(np.median(nums))
print(nums.sum())

100
789
380.4
345.0
1902


In [ ]:
# axis:0 column wise,
# axis:1 row- wise
import numpy as np
mat=np.array([
    [1,2,3,4,5,6],
    [7,8,9,4,5,6]
])
print(mat.sum(axis=1))  # row wise sum
mat.sum(axis=0)  # col wise sum

[21 39]


array([ 8, 10, 12,  8, 10, 12])

In [ ]:
# Boolean indexing
import numpy as np
arr=np.array([10,20,0,0,50])
x=45
arr>x

array([False, False, False, False,  True])

In [ ]:
import numpy as np
arr=np.array([10,20,0,0,50])
x=45
arr[arr>x]   # Boolean indexing / filteration


array([50])

In [ ]:
import numpy as np
mat=np.array([
    [1,2,3,4,5],
    [11,12,13,14,15]
])
idx=mat%2==0
mat[idx]

array([ 2,  4, 12, 14])

In [ ]:
# np.take(): is used to extract specific elements from an array based on given indice
# syntax: np.array(array,indices,axis=none)
import numpy as np
a=np.array([1,2,3,4,5])
np.take(a,[2,4])


array([3, 5])

In [ ]:
# by default - Flatten arrays-> dimension reduces to 1D
import numpy as np
b=np.array([
   [1,2,3,4,5],
   [6,7,8,9,10]
])
np.take(b,[2,6])

array([3, 7])

In [ ]:
# using axis=1 (column wise)
import numpy as np
mat=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(mat)
np.take(mat,[1,3],axis=1)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [ ]:
# using axis =0 (row wise)
import numpy as np
np.take(mat,[0,2],axis=0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [ ]:
# np.put():Replaces array elements at given indices
# syntax: np.put(array,indices[],value[])
import numpy as np
a=np.array([1,2,3,4,5,8])
#print(a)
np.put(a,[0],[10])

In [ ]:
# np.where(): Returns values based on a condition
# syntax: np.where(condition, true_output, false_output)
import numpy as np
a=np.array([1,2,3,4,5,8])
b=np.array([6,7,8,9,10,18])
c=a>2
print(c)
#b==4


[False False  True  True  True  True]


In [ ]:
import numpy as np
x=np.arange(1000)
ans=np.where(x%2==0,"even","odd")
ans[:50]


array(['even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even',
       'odd', 'even', 'odd', 'even', 'odd'], dtype='<U4')

NUMPY IMAGES

In [ ]:
### PIL()-Pillow
### Matplotlib -Plotting
### OpenCV
### Yolo

In [ ]:
#from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np
PATH=r"C:\Users\Reshma\OneDrive\Documents\banff-national-park-lake-minnewanka-600nw-2527379207.jpg"
img=plt.imread(PATH)
np.save("image.npy",img)
image=np.load("image.npy")
image

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Reshma\\OneDrive\\Documents\\banff-national-park-lake-minnewanka-600nw-2527379207.jpg'

In [ ]:
import numpy as np